### ISSUE TITLE
Handling Versioning

### ISSUE THREAD

**Issue by edgar-durand** [qatalog/gcp-config-node#228]
Hello, I just found this awesome library and integrated it in my nestjs api (nestjs/config) with GCP secret manager, it works great, but I am needing to use versions for the secrets, it would be possible to add that feature. I am more than willing to create the PR for it, in case you want it, here is the change I need:

read-value.js
```
async function readValue({
  client,
  file,
  ignoreSecrets,
  prefix,
  project,
  schema,
}) {
  let { env, secret: schemaSecret, version } = schema;
...
const value = await readSecret({ client, project, secret, version });

...

async function readSecret({
  client,
  isRetry = false,
  project,
  secret,
  version,
}) {
  version ??= 'latest';
  try {
    const name = `projects/${project}/secrets/${secret}/versions/${version}`;
```

README.md

```
## How are secrets with multiple versions handled?

The greatest, non-disabled version of the secret will be used by default.
For using a specific version set `version: 'your-version'` in the schema.

```js
const config = await gcpConfig.load({
  project: process.env.GCP_PROJECT,

  schema: {
    foo: {
      version: 1, // Specific version. It is up to you to make sure this version exists or it is enabled.
      secret: 'foo',
    },
  },
});
```

**Comment by phil-booth-qatalog** [comment]
Good idea! Yep, we'd totally take a PR for this if you have time to work on it! :+1:

**Comment by edgar-durand** [comment]
sure thing, grant me access to create the PR, this is my github account: edgarduranddiaz@gmail.com

**Comment by phil-booth-qatalog** [comment]
> grant me access to create the PR

I think there should be no need to grant access?

If you fork the repo here:

https://github.com/qatalog/gcp-config-node/fork

...and then make changes in your fork, it should let you open a pull request from there.

(I just tested this works from my personal account, which also doesn't have permissions in this repo)

**Comment by edgar-durand** [comment]
PR open https://github.com/qatalog/gcp-config-node/pull/230
